services:
  - type: web
    name: youtube-downloader
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api/index.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
